if(DEFINED UMBRA_DEPS_PREFIX)
  set(_umbra_prefix "${UMBRA_DEPS_PREFIX}")
elseif(WIN32 AND MSVC)
  set(_umbra_prefix "${CMAKE_BINARY_DIR}/_deps/msvc")
else()
  set(_umbra_prefix "${CMAKE_CURRENT_LIST_DIR}/../third_party/local")
endif()
set(_umbra_inc "${_umbra_prefix}/include")
set(_umbra_lib "${_umbra_prefix}/lib")
find_path(GMP_INCLUDE_DIR NAMES gmp.h PATHS "${_umbra_inc}" NO_DEFAULT_PATH REQUIRED)
find_library(GMP_LIBRARY NAMES gmp libgmp PATHS "${_umbra_lib}" NO_DEFAULT_PATH REQUIRED)
find_library(GMPXX_LIBRARY NAMES gmpxx libgmpxx PATHS "${_umbra_lib}" NO_DEFAULT_PATH REQUIRED)
find_path(NTL_INCLUDE_DIR NAMES NTL/ZZ.h PATHS "${_umbra_inc}" NO_DEFAULT_PATH REQUIRED)
find_library(NTL_LIBRARY NAMES ntl libntl PATHS "${_umbra_lib}" NO_DEFAULT_PATH REQUIRED)
add_library(GMP::GMP UNKNOWN IMPORTED)
set_target_properties(GMP::GMP PROPERTIES IMPORTED_LOCATION "${GMP_LIBRARY}" INTERFACE_INCLUDE_DIRECTORIES "${GMP_INCLUDE_DIR}")
add_library(GMP::GMPXX UNKNOWN IMPORTED)
set_target_properties(GMP::GMPXX PROPERTIES IMPORTED_LOCATION "${GMPXX_LIBRARY}" INTERFACE_INCLUDE_DIRECTORIES "${GMP_INCLUDE_DIR}" INTERFACE_LINK_LIBRARIES GMP::GMP)
add_library(NTL::NTL UNKNOWN IMPORTED)
set_target_properties(NTL::NTL PROPERTIES IMPORTED_LOCATION "${NTL_LIBRARY}" INTERFACE_INCLUDE_DIRECTORIES "${NTL_INCLUDE_DIR}" INTERFACE_LINK_LIBRARIES GMP::GMP)
